<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'tsmai587_igreja',
	'db_user' => 'tsmai587_webuser',
	'db_password' => 'webuser9009',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.31',
	'mailer_from_name' => 'ocd mkt',
	'mailer_from_email' => 'lukas.freire2011@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '0a3692d5607db3762095cd66a3a1e22c3a00e653246cc84feb37cffa9fd5f46f',
	'site_url' => 'http://tsmail.com.br/projetos/igreja/app',
);
